### ISSUE TITLE
Issue with the filetransfer

### ISSUE THREAD

**Issue by dbzmelvin** [TeamSpeak-Systems/teamspeak-linux-docker-images#10]
I have an Issue on my gce kubernetes environment, that i cant create a loadbalancer that serves multiple ports with different protocols. Would be nice if i can define a different ip for the filetransfer than my actual one for the voice udp.

**Comment by muenchow** [comment]
that is currently not possible.
i will the suggestion to the internal feature development list, and will update the the issue when i have an answer.

**Comment by muenchow** [comment]
We finally went of the next features to be included in the server and decided against adding the feature, sorry.

**Comment by dbzmelvin** [comment]
Mh. Isn't there already the feature to have a different fileserver ip then the voice one?

Something like this
```
filetransfer_port=30033
filetransfer_ip=192.168.1.0,0:0:0:0:0:0:0:1
```

But thanks for the investigation.
