### ISSUE TITLE
Please update the 'latest' tag as it points to an old version.

### ISSUE THREAD

**Issue by Kagenui-yozuru** [TeamSpeak-Systems/teamspeak-linux-docker-images#100]
If you run 
```docker pull teamspeak``` 
or
```docker pull teamspeak:latest```
 you will pull version 3.13.6 instead of 3.13.7. The older version is no longer supported. However, users might be misled by the "latest" tag, just like I was.

**Comment by masonen** [comment]
I think thats outated. Pulled latest yesterday and its 3.13.7

Also the latest tag points to the same digest on dockerhub since 10 months:
![image](https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images/assets/5367729/0ce7a927-0bbe-4b6c-8b60-d9a18a891035)

**Comment by Kagenui-yozuru** [comment]
> I think thats outated. Pulled latest yesterday and its 3.13.7
> 
> Also the latest tag points to the same digest on dockerhub since 10 months: ![image](https://user-images.githubusercontent.com/5367729/259936432-0ce7a927-0bbe-4b6c-8b60-d9a18a891035.png)
> 
> did you restart yoru container after pulling? a running container will never be touched by a pull. Only on next restart it will use the newly pulled version.
> 
> Also make sure that your docker-compose file (if you are running on compose) has not the older tag hardcoded rather than the :latest as it will also run on the later version then.

I'm sorry, I made a mistake. It's possible that I didn't properly restart the Docker container at that time. Thank you for your explanation.
