### ISSUE TITLE
Please provide server files via HTTPS

### ISSUE THREAD

**Issue by r15ch13** [TeamSpeak-Systems/teamspeak-linux-docker-images#11]
https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images/blob/ca34caf6fd01b1e476b34ed65b5cabd898ce71f7/alpine/Dockerfile#L14

**Comment by RiRa12621** [comment]
443 not open on 4players side, so the request would first need to go to them.
`rrackow@LM-TXL-14500969 diaas-schema-registry (jenkins-change)*$ telnet dl.4players.de 80
Trying 85.25.26.25...
Connected to dl.dl1.4players.de.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
rrackow@LM-TXL-14500969 diaas-schema-registry (jenkins-change)*$ telnet dl.4players.de 443
Trying 85.25.26.26...
telnet: connect to address 85.25.26.26: Connection refused
Trying 85.25.26.27...
telnet: connect to address 85.25.26.27: Connection refused
Trying 85.25.26.25...
telnet: connect to address 85.25.26.25: Connection refused
telnet: Unable to connect to remote host`

**Comment by RiRa12621** [comment]
443 is not open on the 4players side
```rrackow@LM-TXL-14500969 ~ $ telnet dl.4players.de 80
Trying 85.25.26.25...
Connected to dl.dl1.4players.de.
Escape character is '^]'.
^]
telnet> quit
Connection closed.
rrackow@LM-TXL-14500969 ~ $ telnet dl.4players.de 443
Trying 85.25.26.27...
telnet: connect to address 85.25.26.27: Connection refused
Trying 85.25.26.26...
telnet: connect to address 85.25.26.26: Connection refused
Trying 85.25.26.25...
telnet: connect to address 85.25.26.25: Connection refused
telnet: Unable to connect to remote host```

**Comment by der-eismann** [comment]
They could also use their own mirror, which supports HTTPS:
`https://files.teamspeak-services.com/releases/server/3.5.0/teamspeak3-server_linux_amd64-3.5.0.tar.bz2`
Another way could be sha512 checksums.

**Comment by der-eismann** [comment]
Thanks for the fix!

**Comment by muenchow** [comment]
with `teamspeak:3.6.0` we switched to https, when we moved the download source to `https://files.teamspeak-services.com`
