### ISSUE TITLE
ServerQuery: help command does not work.

### ISSUE THREAD

**Issue by cebor** [TeamSpeak-Systems/teamspeak-linux-docker-images#3]
When connected to the ServerQuery console and tying `help` i get the following error: 

```
help
error id=1538 msg=invalid\sparameter
```

Workaround: 
Copying or linking help *.txt files from opt to var:
```sh
cp -r /opt/ts3server/serverquerydocs /var/ts3server
# or
ln -s /opt/ts3server/serverquerydocs /var/ts3server

**Comment by muenchow** [comment]
has been fixed with teamspeak:3.3.0
