### ISSUE TITLE
Add support for machine_id and other parameters

### ISSUE THREAD

**Issue by md2k** [TeamSpeak-Systems/teamspeak-linux-docker-images#30]
Hi TeamSpeak, can you add to Docker containers support of next parameters:
* `query_skipbruteforcecheck`
* `machine_id`

Thanks

**Comment by muenchow** [comment]
We will add it with the next server release.

**Comment by Maxpain177** [comment]
@muenchow Please expose these params to ENV.

**Comment by Maxpain177** [comment]
@muenchow please...

**Comment by muenchow** [comment]
@Maxpain177 well since you asked nicely... ;)
It appears we forgot to add this, sorry about that. I will look into that in the next few days,

**Comment by Maxpain177** [comment]
@muenchow Hello! Any news?

**Comment by Maxpain177** [comment]
@muenchow https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images/pull/41

**Comment by muenchow** [comment]
sorry that it took so long,
both options are available in the latest docker, now.
