### ISSUE TITLE
Server ending date is set to one year after creation

### ISSUE THREAD

**Issue by Riordian123** [TeamSpeak-Systems/teamspeak-linux-docker-images#31]
![image](https://user-images.githubusercontent.com/53619676/62382482-eb854600-b54d-11e9-8bde-b95ce1318598.png)

How can I prevent the server from "ending" after one year?

Do I need a non-profit license if I want the server to run longer than a year?

**Comment by muenchow** [comment]
Newer versions of the server, also come with newer version of this `no license`.
If you keep up to date with the server, then you should never run out.
