### ISSUE TITLE
entrypoint.sh: line 50: can't create /var/run/ts3server/ts3server.ini: Permission denied

### ISSUE THREAD

**Issue by It0w** [TeamSpeak-Systems/teamspeak-linux-docker-images#39]
Hallo today i update my docker container from 3.9.1 to 3.10
and get the error
```
/opt/ts3server/entrypoint.sh: line 50: can't create /var/run/ts3server/ts3server.ini: Permission denied
```
i temporary downgrade to 3.9.1 and it runs fine

i use following script for docker

```
docker run -d \
                -p 9987:9987/udp -p 10011:10011 -p 30033:30033 \
                -v /home/ts3server/server:/var/ts3server/ \
                -e TS3SERVER_LICENSE=accept \
                --net docker0 \
                --ip 172.18.0.3 \
                --user $(id -u ts3server):$(id -g ts3server) \
                --name TS3Server \
                teamspeak:latest
```
my configs and licensekey are located in 
```
/home/ts3server/server
```
thanks in advance
Itow

**Comment by nightah** [comment]
Seeing the same issue described here, also had to rollback to `3.9.1`.

**Comment by Hedius** [comment]
I have the same problem.
I already described the problem in the release post:
[[Discussion] TeamSpeak Server 3.10.0](https://forum.teamspeak.com/threads/142032-Discussion-TeamSpeak-Server-3-10-0?p=476490#post476490)

**Comment by nightah** [comment]
Looks like this issue is fixed with `3.10.1`, I think you can close this off now.

**Comment by muenchow** [comment]
yes, still waiting on 3.10.2 coming through before closing.

**Comment by muenchow** [comment]
`teamspeak:3.10.2` got released  for docker. This should fix the permission issues

**Comment by joaonl** [comment]
Additional to above: https://github.com/TeamSpeak-Systems/teamspeak-linux-docker-images/issues/51

Seems like fixing the permissions within the container broke the permissions on mapped volumes.
