### ISSUE TITLE
[question] automatic channel creation

### ISSUE THREAD

**Issue by PortStone** [TeamSpeak-Systems/teamspeak-linux-docker-images#5]
Hello,

is it possible to create a docker TeamSpeak server with already created channels? I want to clone this image  and add my channels. That means (I have installed watchtower) after every update I just need to enter my admin token and don't need to create the channels again.

**Comment by muenchow** [comment]
yes, technically you could add an mysql db to the docker image. But it would be much easier to use use a volumne instead. see https://docs.docker.com/samples/library/teamspeak/#where-to-store-data

**Comment by PortStone** [comment]
yep, works thank you.
I added this to my command line: -v /opt/ts3server:/var/ts3server

Can be closed.
