### ISSUE TITLE
teamspeak aarch64 support

### ISSUE THREAD

**Issue by anuscool** [TeamSpeak-Systems/teamspeak-linux-docker-images#6]
i have requirement to use team speak on aarch64,does it support on aarch64,how i can build it on aarch64

**Comment by anuscool** [comment]
can any one tell me how will i get libts3client.so  libts3server.so  of aarch64 platform,where i will get step 
to build this so file

**Comment by anuscool** [comment]
@muenchow  could you please tell me,how i will build teamspeak  binaries for aarch64,is team speak server source code available for that.

**Comment by muenchow** [comment]
unfortunately there is no aarch64 version of the teamspeak 3 server planned, and the source code, of the server, is proprietary.

**Comment by odidev** [comment]
Hi @muenchow,

Can you please let me know, what needs to be done get support for ```arm64v8``` for ```Teamspeak``` module.
I am open to both the approaches, either source code compilation for ```arm64v8``` or get prebuilt binaries for ```arm64v8```.

In case, if you are worried about infrastructure to support ```arm64v8``` then,
```
Shippable supports free Arm64 CI/CD and I believe Codefresh does too (both 64-bit and 32-bit for both providers):

https://blog.shippable.com/shippable-arm-packet-deliver-native-ci-cd-for-arm-architecture
http://docs.shippable.com/platform/tutorial/workflow/run-ci-builds-on-arm/

CodeFresh Beta signup: https://goo.gl/forms/aDhlk56jZcblYokj1

If you need raw infrastructure the WorksOnArm project will supply full servers if you want to deal with metal: https://github.com/worksonarm/cluster/
```
We can have a separate discussion as well over the mail if you agree for the same.

Regards,

**Comment by muenchow** [comment]
Hi @odidev,
we currently have no plans on adding support for `arm64v8`, sorry.

**Comment by odidev** [comment]
Hi @muenchow - I do understand that you do not have any plans right now for ```arm64v8``` :disappointed: 
But still, it would be great if you can share your concerns regarding ```what is blocking you to support arm```.

May be, by this we will be better aware of what we both are thinking.

You must be having some of the scenarios, which I can't think about and those are stopping you to support ```arm```

Regards,

**Comment by muenchow** [comment]
I am teribbly sorry @odidev, but i can not divulge anymore information.

**Comment by mahehro** [comment]
Can you please revive this problem? More and more clients and servers are running on arm architecture and support for arm cpus would be really great...

**Comment by sharknoon** [comment]
Is there any option to reconsider arm64 support? Raspberry Pis are getting really fast nowadays, the first Windows notebooks with arm chips (Qualcomm Snapdragen X Pro/Elite) are appearing and big cloud providers like AWS are offering more and more ARM based servers. It would be a bummer to be stuck with x86 emulation for teamspeak
