### ISSUE TITLE
It always creates a new vTeamspeak Server

### ISSUE THREAD

**Issue by fortiZde** [TeamSpeak-Systems/teamspeak-linux-docker-images#7]
I want to switch from an own written docker-file to this official one. I now use docker-compose for mariadb and teamspeak. Everytime I started the composition it creates a new server instead of using the existing one.

**Comment by ArcticXWolf** [comment]
Hey, how did you solve this?

I have the same problem, it always creates a new virtual server on startup and I have to manually stop and start the correct one via the query api.
