### ISSUE TITLE
Checksum check is not enforced in Dockerfile

### ISSUE THREAD

**Issue by csware** [TeamSpeak-Systems/teamspeak-linux-docker-images#75]
Because `;` is used to concatenate commands for the RUN activity instead of `&&` the docker image can be created even if the checksum test fails.

Solution: Better use `&&` instead of `;`

**Comment by muenchow** [comment]
Did test this assertion before posting? I am asking because, when looking at the relevant script, there is an initial `set -e` that should terminate the whole `RUN` if any of the commands fail.

```
RUN set -eux; \
    [...]
    wget "${TEAMSPEAK_URL}" -O server.tar.bz2; \
    echo "${TEAMSPEAK_CHECKSUM} *server.tar.bz2" | sha256sum -c -; \
    [...]
```

**Comment by csware** [comment]
Argh. You are right. (I spotted this issue in multiple Dockerfiles, but I oversay the `set -e`part in this case.

Sorry for the noise.
