### ISSUE TITLE
Accounting problems after switching to docker

### ISSUE THREAD

**Issue by Gamewalker** [TeamSpeak-Systems/teamspeak-linux-docker-images#8]
> 2018-08-15 03:21:20.802713|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.3.0 (2018-07-31 16:10:01)
> 2018-08-15 03:21:20.802927|INFO    |ServerLibPriv |   |SystemInformation: Linux 4.13.0-39-generic #44~16.04.1-Ubuntu SMP Thu Apr 5 16:43:10 UTC 2018 x86_64 Binary: 64bit
> 2018-08-15 03:21:20.802969|INFO    |ServerLibPriv |   |Using hardware aes
> 2018-08-15 03:21:20.803193|INFO    |DatabaseQuery |   |dbPlugin name:    SQLite3 plugin, Version 3, (c)TeamSpeak Systems GmbH
> 2018-08-15 03:21:20.803244|INFO    |DatabaseQuery |   |dbPlugin version: 3.11.1
> 2018-08-15 03:21:20.803401|INFO    |DatabaseQuery |   |checking database integrity (may take a while)
> 2018-08-15 03:21:20.830174|INFO    |Accounting    |   |Licensing Information
> 2018-08-15 03:21:20.830217|INFO    |Accounting    |   |type              : Non-Profit License
> 2018-08-15 03:21:20.830245|INFO    |Accounting    |   |starting date     : Tue May  1 00:00:00 2018
> 2018-08-15 03:21:20.830267|INFO    |Accounting    |   |ending date       : Sun Nov 18 00:00:00 2018
> 2018-08-15 03:21:20.830286|INFO    |Accounting    |   |max virtualservers: 10
> 2018-08-15 03:21:20.830305|INFO    |Accounting    |   |max slots         : 512
> 2018-08-15 03:21:21.239504|INFO    |              |   |Puzzle precompute time: 393
> 2018-08-15 03:21:21.240037|INFO    |FileManager   |   |listening on 0.0.0.0:30033, [::]:30033
> 2018-08-15 03:21:25.826857|INFO    |ServerLibPriv |   |failed to download revocation list - count: 1
> 2018-08-15 03:21:25.836336|ERROR   |Accounting    |   |Error contacting server https://accounting2.teamspeak.com: RESOLVE_ERROR: Host not found (non-authoritative), try again later
> 2018-08-15 03:21:30.841844|ERROR   |Accounting    |   |Error contacting server https://backupaccounting2.teamspeak.com: RESOLVE_ERROR: Host not found (non-authoritative), try again later
> 2018-08-15 03:21:30.841905|ERROR   |Accounting    |   |Unable to connect to accounting server
> 2018-08-15 03:21:31.250600|ERROR   |              |   |TS3ANetwork::ResolveHostName failed error: -3 (Try again) 22
> 2018-08-15 03:21:31.250655|ERROR   |              |   |Could not open default UDP connection for weblist
> 2018-08-15 03:21:31.265187|INFO    |VirtualServer |2  |listening on 0.0.0.0:9987, [::]:9987
> 2018-08-15 03:21:31.270086|INFO    |Query         |   |listening for query on 0.0.0.0:10011, [::]:10011
> 2018-08-15 03:21:31.270163|INFO    |CIDRManager   |   |updated query_ip_whitelist ips: 127.0.0.1/32, ::1/128, 
> 2018-08-15 03:21:33.576197|INFO    |VirtualServerBase|2  |rejecting myteamspeakid: revoke list out of date
> 2018-08-15 03:21:33.576257|INFO    |VirtualServerBase|2  |client is connecting with a invalid or revoked myTeamSpeak ID
> 2018-08-15 03:21:34.046970|INFO    |VirtualServerBase|2  |rejecting myteamspeakid: revoke list out of date
> 2018-08-15 03:21:34.047016|INFO    |VirtualServerBase|2  |failed to update myTeamSpeak ID

After I switched to docker, I get these errors. I opened port 2008/tcp on my host but this doesnt help. Any ideas?

**Comment by muenchow** [comment]
From what i tell it might have something to do with internet access. All the errors in your log are related it. 
You might want to check if the docker has access to the internet, that might solve your problems.

**Comment by muenchow** [comment]
It is not only the accounting that fails. As for ports: the teamspeak server needs to be able to connect to teamspeak.com sub domains using port 443 and not 2008. The later port isn't used in modern servers anymore.
