### ISSUE TITLE
A few issues, unable to translate FQDN and SECRETS not supported

### ISSUE THREAD

**Issue by tessierp** [TeamSpeak-Systems/teamspeak-linux-docker-images#87]
Hi, I have the following docker-compose : 

`---
version: "3.9"
services:
  teamspeak:
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
    image: teamspeak:latest
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    networks:
      - comms-net
    environment:
      - TS3SERVER_DB_PLUGIN: ts3db_postgresql
      - TS3SERVER_DB_SQLCREATEPATH: create_postgresql
      - TS3SERVER_DB_HOST: xxx.xxx.xxx.xxx
      - TS3SERVER_DB_PORT: 5432
      - TS3SERVER_DB_USER: teamspeak
      - TS3SERVER_DB_PASSWORD: /run/secrets/teamspeak-db-password
      - TS3SERVER_DB_NAME: teamspeak
      - TS3SERVER_DB_WAITUNTILREADY: 30
      - TS3SERVER_LICENSE: accept
    volumes:
      - teamspeak-config:/var/ts3server/
    secrets:
      - teamspeak-db-password

secrets:
  teamspeak-db-password:
    external: true

volumes:
  teamspeak-config:
    external: true

networks:
  comms-net:
    driver: overlay
    attachable: true`

I was unable to use secrets and I'm assuming because the container doesn't support secrets. I had to pass the password directly in the compose file. The caveat with that is I have to remember to remove the credentials after.

Also, under TS3SERVER_DB_HOST, if I put down the FQDN, it is unable to find the server, probably doesn't have access to the DNS so the ability to add local DNS would be nice. Problem resolved by adding the IP.

**Comment by muenchow** [comment]
There is support for secrets:
`TS3SERVER_DB_HOST`, `TS3SERVER_DB_USER`, `TS3SERVER_DB_PASSWORD` and `TS3SERVER_DB_NAME` support getting there values from a file by appending `_FILE` to there name. For example
`TS3SERVER_DB_PASSWORD_FILE: /run/secrets/teamspeak-db-password` would be the solution for your problem.

As for you dns problem:
AFAIK the ts3server is using the dns resolver provided by the system/docker.

p.s.: i very much doubt you have been using a FQDN, in fact you most likely had been using a PQDN, or domain names as we like to call them.

**Comment by tessierp** [comment]
Hi, you are correct, it is indeed a PQDN. However it still doesn't work. I am not exactly sure why as I am able to ping the PQDN from the system.

I tried TS3SERVER_DB_PASSWORD_FILE: /run/secrets/teamspeak-db-password and that did solve this issue, thank you!
