### ISSUE TITLE
Missing ld-linux-x86-64.so.2

### ISSUE THREAD

**Issue by jmwri** [TeamSpeak-Systems/teamspeak-linux-docker-images#9]
I am unable to start up ts3 using the `ts3db_mysql` plugin.

I am trying to use MySQL instead of sqlite so added all of the env vars as described in the readme, but changed MariaDB to MySQL as I am not using MariaDB.

```
2018-08-16 16:24:04.444896|INFO    |ServerLibPriv |   |TeamSpeak 3 Server 3.3.0 (2018-07-31 16:10:01)
2018-08-16 16:24:04.445217|INFO    |ServerLibPriv |   |SystemInformation: Linux 4.4.0-131-generic #157-Ubuntu SMP Thu Jul 12 15:51:36 UTC 2018 x86_64 Binary: 64bit
2018-08-16 16:24:04.445332|INFO    |ServerLibPriv |   |Using hardware aes
2018-08-16 16:24:04.445570|INFO    |DatabaseQuery |   |Please make sure you use the supplied ts3server_minimal_runscript.sh to run the server, or set LD_LIBRARY_PATH yourself
2018-08-16 16:24:04.445686|CRITICAL|DatabaseQuery |   |unable to load database plugin library "libts3db_mysql.so", halting!
```

I have set the following env vars:

- TS3SERVER_DB_PLUGIN=ts3db_mysql
- TS3SERVER_DB_SQLCREATEPATH=create_mysql
- TS3SERVER_DB_HOST=my host
- TS3SERVER_DB_USER=my user
- TS3SERVER_DB_PASSWORD=my pw
- TS3SERVER_DB_NAME=my db
- TS3SERVER_DB_WAITUNTILREADY=30
- TS3SERVER_LICENSE= accept

Have I missed something?

EDIT:

If I set `LD_LIBRARY_PATH: /var/ts3server` I get the following error:

````
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /var/ts3server/libts3_ssh.so)
````

Maybe there is a missing dependency?

**Comment by Bluscream** [comment]
@muenchow didn't make it really clear: mysql is not supported anymore. Your only options are MariaDB or SQLite.

**Comment by jmwri** [comment]
@muenchow I saw mariadb was used in the example but I also noticed `lobts3db_mysql.so` in `/var/ts3server`.

@Bluscream Is MySQL not supported by ts3, or just this container?

**Comment by jmwri** [comment]
@muenchow I tried that but got an error about the database not being in the correct format for mariadb. So far I just made the sqlite dump compatible with MySQL.

**Comment by muenchow** [comment]
@jmwri  The docker does not contain a file called `lobts3db_mysql.so` file. I do not know what docker you are using, but apparently it is not this one.

**Comment by muenchow** [comment]
@jmwri it seams you are using a mysql 8.0 server. Unfortunately we won't be able to support `caching_sha2_password` as mariadb is not going to support it. See https://jira.mariadb.org/browse/CONC-312
The `libts3db_mysql.so` will also be not of any help, as it will be much to old to have support for `authentication`.
As a possible solutions i would recommend changing the authentication back to `mysql_native_password` or using mariadb.

**Comment by jmwri** [comment]
@muenchow Got it working with MySQL apart from hopefully the last error...
```
This database does not seem to be prepared for the new mariadb format. Please read the file on updating the database in doc/update_mysql_to_mariadb.txt
```

I can't seem to find the file anywhere, could you point me in the right direction please?

**Comment by muenchow** [comment]
@jmwri You can find the file in the docker at `/opt/ts3server/doc/update_mysql_to_mariadb.txt`.
Alternatively the file can also be found in any of the server releases found [here](https://www.teamspeak.com/en/downloads#server)

**Comment by jmwri** [comment]
@muenchow Thanks for all your help. Running on MySQL now :)!
